// <auto-generated />
using Emergency_Services_Locator.Backend;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Emergency_Services_Locator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215164123_postgresNewInstall")]
    partial class postgresNewInstall
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Emergency_Services_Locator.Backend.Models.Facility", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int?>("Mapid")
                        .HasColumnType("integer");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("contact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("facility_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<int>("map_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("Mapid");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("Emergency_Services_Locator.Backend.Models.Map", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<bool>("isDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("boolean");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("location_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("Emergency_Services_Locator.Backend.Models.Facility", b =>
                {
                    b.HasOne("Emergency_Services_Locator.Backend.Models.Map", null)
                        .WithMany("facilities")
                        .HasForeignKey("Mapid");
                });

            modelBuilder.Entity("Emergency_Services_Locator.Backend.Models.Map", b =>
                {
                    b.Navigation("facilities");
                });
#pragma warning restore 612, 618
        }
    }
}
